//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Bix.Mixers.Fody.Config {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Bix:Mixers:Fody:Config")]
    [System.Xml.Serialization.XmlRootAttribute("BixMixersConfig", Namespace="urn:Bix:Mixers:Fody:Config", IsNullable=false)]
    public partial class BixMixersConfigType {
        
        private MixCommandConfigTypeBase[] mixCommandConfigField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MixCommandConfig", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MixCommandConfigTypeBase[] MixCommandConfig {
            get {
                return this.mixCommandConfigField;
            }
            set {
                this.mixCommandConfigField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceMixinConfigType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Bix:Mixers:Fody:Config")]
    public abstract partial class MixCommandConfigTypeBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Bix:Mixers:Fody:Config")]
    public partial class InterfaceMixinMapType {
        
        private string interfaceField;
        
        private string mixinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Interface {
            get {
                return this.interfaceField;
            }
            set {
                this.interfaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mixin {
            get {
                return this.mixinField;
            }
            set {
                this.mixinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Bix:Mixers:Fody:Config")]
    [System.Xml.Serialization.XmlRootAttribute("InterfaceMixinConfig", Namespace="urn:Bix:Mixers:Fody:Config", IsNullable=false)]
    public partial class InterfaceMixinConfigType : MixCommandConfigTypeBase {
        
        private InterfaceMixinMapType[] interfaceMixinMapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterfaceMixinMap", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfaceMixinMapType[] InterfaceMixinMap {
            get {
                return this.interfaceMixinMapField;
            }
            set {
                this.interfaceMixinMapField = value;
            }
        }
    }
}
